# filepath: d:\PROJETS\baskshop\.github\workflows\symfony.yml
on: [pull_request]
name: Main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git to trust the repository directory
        run: git config --global --add safe.directory /app

      - uses: actions/checkout@v3

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.2

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Fix directory permissions
        run: sudo chown -R $USER:$USER .

      - name: Remove vendor directory
        run: rm -rf vendor composer.lock

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check if MakerBundle is installed
        run: |
          if ! composer show | grep -q "symfony/maker-bundle"; then
            composer require symfony/maker-bundle --dev
          fi

      - name: Clear Symfony cache
        run: php bin/console cache:clear --env=prod || rm -rf var/cache/*

      - name: Regenerate autoload
        run: composer dump-autoload --optimize

      - name: Cache Composer store
        uses: actions/cache@v3
        with:
          path: ~/vendor
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.OS }}-composer-

      - name: Lint PHP
        run: find . -name "*.php" -type f -not -path "./vendor/*" -not -path "./var/*" -exec php -l {} \;

      - name: Lint Style
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

      - name: Setup test db
        run: php bin/console doctrine:database:create --env=test

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test -n

      - name: Run tests
        run: vendor/bin/phpunit